apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - port: 5000 # Service port di cluster
      targetPort: 5000 # port di dalam container
